version: '3'

services:

  app:
    build: .docker/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 100s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - nhecosystem-api
    depends_on:
      - db
      # - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8500:80"
    volumes:
      - .:/var/www
    networks:
      - nhecosystem-api
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=central_depositaria
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nhecosystem-api

  # redis:
  #     image: redis:alpine
  #     container_name: redis
  #     expose:
  #         - 6379
  #     networks:
  #         - nhecosystem-api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9500:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=1024M
      - MAX_EXECUTION_TIME=0
      - UPLOAD_LIMI= 6096K
    depends_on:
      - db
    networks:
      - nhecosystem-api

networks:
  nhecosystem-api:
    driver: bridge
